# Generated by Django 4.2.6 on 2023-10-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.ManyToManyField(blank=True, to='bank.credit'),
        ),
    ]
