# Generated by Django 4.2.6 on 2023-10-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_account_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='credit',
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.ManyToManyField(to='bank.credit'),
        ),
    ]
