# Generated by Django 4.2.6 on 2023-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
